/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './__root'
import { Route as _layoutRouteImport } from './__layout'
import { Route as _layoutIndexRouteImport } from './__layout/index'
import { Route as AuthSignUpRouteImport } from './auth/signUp'
import { Route as AuthLoginRouteImport } from './auth/login'
import { Route as Auth_layoutRouteImport } from './auth/__layout'
import { Route as AuthForgotPasswordRouteImport } from './auth/ForgotPassword'
import { Route as _layoutSettingsRouteImport } from './__layout/settings'
import { Route as _layoutProfileRouteImport } from './__layout/profile'
import { Route as _layoutMessageRouteImport } from './__layout/message'
import { Route as _layoutFriendRouteImport } from './__layout/friend'
import { Route as _layoutFriendIndexRouteImport } from './__layout/friend/index'
import { Route as _layoutFriendAddRouteImport } from './__layout/friend/add'

const AuthRouteImport = createFileRoute('/auth')()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutIndexRoute = _layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _layoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/ForgotPassword',
  path: '/auth/ForgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutSettingsRoute = _layoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutProfileRoute = _layoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutMessageRoute = _layoutMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutFriendRoute = _layoutFriendRouteImport.update({
  id: '/friend',
  path: '/friend',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutFriendIndexRoute = _layoutFriendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _layoutFriendRoute,
} as any)
const _layoutFriendAddRoute = _layoutFriendAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => _layoutFriendRoute,
} as any)

export interface FileRoutesByFullPath {
  '/friend': typeof _layoutFriendRouteWithChildren
  '/message': typeof _layoutMessageRoute
  '/profile': typeof _layoutProfileRoute
  '/settings': typeof _layoutSettingsRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/': typeof _layoutIndexRoute
  '/friend/add': typeof _layoutFriendAddRoute
  '/friend/': typeof _layoutFriendIndexRoute
}
export interface FileRoutesByTo {
  '/message': typeof _layoutMessageRoute
  '/profile': typeof _layoutProfileRoute
  '/settings': typeof _layoutSettingsRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/': typeof _layoutIndexRoute
  '/friend/add': typeof _layoutFriendAddRoute
  '/friend': typeof _layoutFriendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__layout': typeof _layoutRouteWithChildren
  '/__layout/friend': typeof _layoutFriendRouteWithChildren
  '/__layout/message': typeof _layoutMessageRoute
  '/__layout/profile': typeof _layoutProfileRoute
  '/__layout/settings': typeof _layoutSettingsRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/__layout': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signUp': typeof AuthSignUpRoute
  '/__layout/': typeof _layoutIndexRoute
  '/__layout/friend/add': typeof _layoutFriendAddRoute
  '/__layout/friend/': typeof _layoutFriendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/friend'
    | '/message'
    | '/profile'
    | '/settings'
    | '/auth/ForgotPassword'
    | '/auth'
    | '/auth/login'
    | '/auth/signUp'
    | '/'
    | '/friend/add'
    | '/friend/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/message'
    | '/profile'
    | '/settings'
    | '/auth/ForgotPassword'
    | '/auth'
    | '/auth/login'
    | '/auth/signUp'
    | '/'
    | '/friend/add'
    | '/friend'
  id:
    | '__root__'
    | '/__layout'
    | '/__layout/friend'
    | '/__layout/message'
    | '/__layout/profile'
    | '/__layout/settings'
    | '/auth/ForgotPassword'
    | '/auth'
    | '/auth/__layout'
    | '/auth/login'
    | '/auth/signUp'
    | '/__layout/'
    | '/__layout/friend/add'
    | '/__layout/friend/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _layoutRoute: typeof _layoutRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/': {
      id: '/__layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _layoutIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/auth/signUp': {
      id: '/auth/signUp'
      path: '/signUp'
      fullPath: '/auth/signUp'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/ForgotPassword': {
      id: '/auth/ForgotPassword'
      path: '/auth/ForgotPassword'
      fullPath: '/auth/ForgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/settings': {
      id: '/__layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _layoutSettingsRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/profile': {
      id: '/__layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof _layoutProfileRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/message': {
      id: '/__layout/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof _layoutMessageRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/friend': {
      id: '/__layout/friend'
      path: '/friend'
      fullPath: '/friend'
      preLoaderRoute: typeof _layoutFriendRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/friend/': {
      id: '/__layout/friend/'
      path: '/'
      fullPath: '/friend/'
      preLoaderRoute: typeof _layoutFriendIndexRouteImport
      parentRoute: typeof _layoutFriendRoute
    }
    '/__layout/friend/add': {
      id: '/__layout/friend/add'
      path: '/add'
      fullPath: '/friend/add'
      preLoaderRoute: typeof _layoutFriendAddRouteImport
      parentRoute: typeof _layoutFriendRoute
    }
  }
}

interface _layoutFriendRouteChildren {
  _layoutFriendAddRoute: typeof _layoutFriendAddRoute
  _layoutFriendIndexRoute: typeof _layoutFriendIndexRoute
}

const _layoutFriendRouteChildren: _layoutFriendRouteChildren = {
  _layoutFriendAddRoute: _layoutFriendAddRoute,
  _layoutFriendIndexRoute: _layoutFriendIndexRoute,
}

const _layoutFriendRouteWithChildren = _layoutFriendRoute._addFileChildren(
  _layoutFriendRouteChildren,
)

interface _layoutRouteChildren {
  _layoutFriendRoute: typeof _layoutFriendRouteWithChildren
  _layoutMessageRoute: typeof _layoutMessageRoute
  _layoutProfileRoute: typeof _layoutProfileRoute
  _layoutSettingsRoute: typeof _layoutSettingsRoute
  _layoutIndexRoute: typeof _layoutIndexRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutFriendRoute: _layoutFriendRouteWithChildren,
  _layoutMessageRoute: _layoutMessageRoute,
  _layoutProfileRoute: _layoutProfileRoute,
  _layoutSettingsRoute: _layoutSettingsRoute,
  _layoutIndexRoute: _layoutIndexRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

interface AuthRouteChildren {
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth_layoutRoute: Auth_layoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _layoutRoute: _layoutRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
